# Generated by Django 4.2.1 on 2023-05-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
