# Generated by Django 4.2.1 on 2023-05-23 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('b', 'Borrowed'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book copy availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book')),
            ],
            options={
                'ordering': ['book'],
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('refuse_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('r', 'Returned'), ('p', 'Pending'), ('b', 'Borrowing'), ('c', 'Canceled'), ('d', 'Declined')], default='p', help_text='Borrowing quest status', max_length=1)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.bookcopy')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
