# Generated by Django 4.2.1 on 2023-05-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bookcopy_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='borrowing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
