# Generated by Django 4.2.1 on 2023-05-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_borrowing_options_borrowing_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-updated_at']},
        ),
    ]
