# Generated by Django 4.2.1 on 2023-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_refuse_reason_borrowing_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Canceled'), ('a', 'Approved'), ('d', 'Declined'), ('b', 'Borrowing'), ('r', 'Returned')], default='p', help_text='Borrowing quest status', max_length=1),
        ),
    ]
